name: aq

on:
  push:

jobs:
  lint-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-3|${{ env.pythonLocation }}|${{ hashFiles('.pre-commit-config.yaml') }}
      - run: python -m pip install pre-commit
      - uses: abatilo/actions-poetry@v2
      - run: poetry install
      - run: poetry run pre-commit run --show-diff-on-failure --color=always --all
